server:
  port: 8000
  address: 0.0.0.0

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://linkbig-ht-20.czwmu86ms4yl.us-east-1.rds.amazonaws.com:3306/hiresense?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: hiresense12
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # In production, use 'validate' or 'none'
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    s3:
      bucket: linkbig-ht-20-ai-interview-storage
