server:
  port: 8000
  address: 0.0.0.0

spring:
  profiles:
    active: dev

cloud:
  aws:
    region:
      static: us-east-1



# Bedrock 모델 ID
bedrock:
  model-id: "anthropic.claude-3-sonnet-20240229-v1:0"
  region: "us-east-1"
  guardrail-identifier: "gi0pmpvfbz8t"

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000  # 1 hour (access token)
  refresh-expiration: 604800000  # 7 days (refresh token)